#!/bin/bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
cd /home/ec2-user/lp-juri
nvm install 16
npm install next react react-dom
killall node
npm run build
npm run start > app.out.log 2> app.err.log < /dev/null & 